### ISSUE TITLE
HomeKit - Not found in Home

### ISSUE THREAD

**Issue by FrankDoersam** [automatica-core/automatica#11]
Good day, the project is really great! Unfortunately, the server is not displayed in homekit on the iphone, I have already opened the firewall and the server is running as an admin. I would be very thankful to you for help! Thanks in advance. best regards frank

**Comment by p3root** [comment]
Hey Frank!

I need more information from you.

Which version do you use? 0.8?
Which system do you use?

Can you provide me log files?


p3

**Comment by FrankDoersam** [comment]
I use the repository https://github.com/automatica-core/automatica.driver.homekit

I Start the Console Test under Windows 10.
do I have to make changes to the code before?

**Comment by FrankDoersam** [comment]
when I open the app home on the iPhone and want to add a new device, I'm nodding the server appears. both devices are in the same network.

**Comment by p3root** [comment]
Hey Frank!

I have updated the console application for you. You can find it in the develop branch. 
173127a99f86a8a6d8435d5b60d34e09a0557dfc

The HomeKit driver should only be used with the automatica.core system! It is not thought to be used otherwise. Also in the future, the code can change in any way that it does only work the automatica.core system.


p3

**Comment by FrankDoersam** [comment]
Think you!
Could you Tell me where  the error was ?

**Comment by p3root** [comment]
Check the diff
https://github.com/automatica-core/automatica/commit/173127a99f86a8a6d8435d5b60d34e09a0557dfc

p3
